### ISSUE TITLE
Add source license

### ISSUE THREAD

**Issue by MarcoPNS** [TiFu/skyscanner-tsp#1]
Currently, this project has no license and therefore is automatically fully copyrighted.
This makes it (nearly) impossible to contribute to the codebase.

Could you change it? You project is awesome!

**Comment by viluon** [comment]
Thanks for the kind words @MarcoPNS. I believe we wanted to use MIT or GPL, is that right, @TiFu?

**Comment by TiFu** [comment]
Thanks a lot! @MarcoPNS 

Yeah, either MIT or GPL is fine with me. I have a slight preference for GPL. 
Just takled to @jtren, she is fine with both. 

@delold any preference?

**Comment by dqbd** [comment]
GPL seems fine for me.

PS: thanks @MarcoPNS 😄
